spring:
  application:
    name: pandac-store-backend
  # Disabled SQL init in favor of Flyway migrations
  # sql:
  #   init:
  #     mode: always
  #     schema-locations: optional:classpath:sql/schema.sql
  #     data-locations: optional:classpath:sql/data.sql
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:pandac}
    username: ${DATABASE_USERNAME:app}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate  # Changed from default to validate for production safety
    show-sql: ${JPA_SHOW_URL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: ${HIBERNATE_FORMAT_SQL:true}
  # Flyway configuration
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
  servlet:
    multipart:
      max-file-size: ${FILE_MAX_SIZE:10MB}
      max-request-size: ${FILE_MAX_REQUEST_SIZE:10MB}
  # profiles:
  #   active: prod

# debug: true

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
    file: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c","message":"%m"}'
  level:
    root: ${LOG_LEVEL:INFO}
  file:
    name: ${LOG_FILE_NAME:./logs/app.log}

management:
  endpoint:
    health:
      show-details: always
    configprops:
      show-values: always
    env:
      show-values: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        # exclude: beans,health
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: E-commerce application
    version: 1.0.0
    contact:
      email: 4TtG3@example.com

contact:
  phone: +91-1234567890
  email: dev@pandac.in
  address: 123 Main Street, Anytown, USA

app:
  file:
    upload-dir: ${FILE_UPLOAD_DIR:uploads/images}
    max-file-size: ${FILE_MAX_SIZE:10MB}
    max-request-size: ${FILE_MAX_REQUEST_SIZE:10MB}
  git:
    repository-url: ${GIT_REPO_URL:https://github.com/pandaind/pandac-store-cdn.git}
    username: ${GIT_USERNAME:pandaind}
    token: ${GIT_TOKEN}
    cdn-base-url: ${CDN_BASE_URL:https://cdn.jsdelivr.net/gh}
