# Docker-specific configuration for Spring Boot
spring:
  application:
    name: pandac-store-backend
  
  # Database configuration for Docker
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:mysql}:${DATABASE_PORT:3306}/${DATABASE_NAME:pandac}
    username: ${DATABASE_USERNAME:app}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_URL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: ${HIBERNATE_FORMAT_SQL:false}
  
  # Flyway configuration
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    
  servlet:
    multipart:
      max-file-size: ${FILE_MAX_SIZE:10MB}
      max-request-size: ${FILE_MAX_REQUEST_SIZE:10MB}

# Application-specific configuration
app:
  file:
    upload-dir: ${FILE_UPLOAD_DIR:uploads/images}
    max-file-size: ${FILE_MAX_SIZE:10MB}
    max-request-size: ${FILE_MAX_REQUEST_SIZE:10MB}
  git:
    repository-url: ${GIT_REPO_URL}
    username: ${GIT_USERNAME}
    token: ${GIT_TOKEN}
    cdn-base-url: ${CDN_BASE_URL}

# Actuator configuration for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# Logging configuration
logging:
  level:
    root: INFO
    '[in.pandac.store]': INFO
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"